package https.api_baidu_com.sem.sms.v3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-10-13T00:18:41.540+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "https://api.baidu.com/sem/sms/v3", name = "ReportService")
@XmlSeeAlso({com.baidu.api.sem.common.v2.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ReportService {

    @WebResult(name = "getRealTimeDataResponse", targetNamespace = "https://api.baidu.com/sem/sms/v3", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/sms/v3/ReportService/getRealTimeData")
    public GetRealTimeDataResponse getRealTimeData(
        @WebParam(partName = "parameters", name = "getRealTimeDataRequest", targetNamespace = "https://api.baidu.com/sem/sms/v3")
        GetRealTimeDataRequest parameters
    );

    @WebResult(name = "getReportFileUrlResponse", targetNamespace = "https://api.baidu.com/sem/sms/v3", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/sms/v3/ReportService/getReportFileUrl")
    public GetReportFileUrlResponse getReportFileUrl(
        @WebParam(partName = "parameters", name = "getReportFileUrlRequest", targetNamespace = "https://api.baidu.com/sem/sms/v3")
        GetReportFileUrlRequest parameters
    );

    @WebResult(name = "getRealTimePairDataResponse", targetNamespace = "https://api.baidu.com/sem/sms/v3", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/sms/v3/ReportService/getRealTimePairData")
    public GetRealTimePairDataResponse getRealTimePairData(
        @WebParam(partName = "parameters", name = "getRealTimePairDataRequest", targetNamespace = "https://api.baidu.com/sem/sms/v3")
        GetRealTimePairDataRequest parameters
    );

    @WebResult(name = "getReportStateResponse", targetNamespace = "https://api.baidu.com/sem/sms/v3", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/sms/v3/ReportService/getReportState")
    public GetReportStateResponse getReportState(
        @WebParam(partName = "parameters", name = "getReportStateRequest", targetNamespace = "https://api.baidu.com/sem/sms/v3")
        GetReportStateRequest parameters
    );

    @WebResult(name = "getRealTimeQueryDataResponse", targetNamespace = "https://api.baidu.com/sem/sms/v3", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/sms/v3/ReportService/getRealTimeQueryData")
    public GetRealTimeQueryDataResponse getRealTimeQueryData(
        @WebParam(partName = "parameters", name = "getRealTimeQueryDataRequest", targetNamespace = "https://api.baidu.com/sem/sms/v3")
        GetRealTimeQueryDataRequest parameters
    );

    @WebResult(name = "getProfessionalReportIdResponse", targetNamespace = "https://api.baidu.com/sem/sms/v3", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/sms/v3/ReportService/getProfessionalReportId")
    public GetProfessionalReportIdResponse getProfessionalReportId(
        @WebParam(partName = "parameters", name = "getProfessionalReportIdRequest", targetNamespace = "https://api.baidu.com/sem/sms/v3")
        GetProfessionalReportIdRequest parameters
    );
}
